/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EjercicioGit;

public class NewMain {
public static void main(String[] args) {
System.out.println(Sumador.sumar (15f,4f));
}}
